#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-fst
Version  : 2.24
Release  : 2
URL      : https://github.com/RuedigerMoeller/fast-serialization/archive/2.24.tar.gz
Source0  : https://github.com/RuedigerMoeller/fast-serialization/archive/2.24.tar.gz
Source1  : https://repo1.maven.org/maven2/de/ruedigermoeller/fst/2.24/fst-2.24.jar
Source2  : https://repo1.maven.org/maven2/de/ruedigermoeller/fst/2.24/fst-2.24.pom
Source3  : https://repo1.maven.org/maven2/de/ruedigermoeller/fst/2.50/fst-2.50.jar
Source4  : https://repo1.maven.org/maven2/de/ruedigermoeller/fst/2.50/fst-2.50.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-fst-data = %{version}-%{release}

%description
fast-serialization
==================
* 100% JDK Serialization compatible drop-in replacement (Ok, might be 99% ..).
* OffHeap Maps, Persistent OffHeap maps
* FSTStructs is very similar to IBM's packed objects. Difference is: You can run it with Oracle JDK today.
* should be Android compatible since version >= 2.17
* Apache 2.0 license since 2.17

%package data
Summary: data components for the mvn-fst package.
Group: Data

%description data
data components for the mvn-fst package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.24
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.24/fst-2.24.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.24
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.24/fst-2.24.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.50
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.50/fst-2.50.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.50
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.50/fst-2.50.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.24/fst-2.24.jar
/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.24/fst-2.24.pom
/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.50/fst-2.50.jar
/usr/share/java/.m2/repository/de/ruedigermoeller/fst/2.50/fst-2.50.pom
